export const UI = {
  OPEN_MODAL: "OPEN_MODAL",
  CLOSE_MODAL: "CLOSE_MODAL",
  MODAL_DATA: "MODAL_DATA"
};

export const AUTH = {
  LOAD: "AUTH_LOAD",
  CLEAR: "AUTH_CLEAR",
  SET_CONNECTED_USER: "SET_CONNECTED_USER",
  SET_NOT_CONNECTED_USER: "SET_NOT_CONNECTED_USER",
  WALLET_CONNECTED: "WALLET_CONNECTED",
  WALLET_ADDRESS: "WALLET_ADDRESS",
  WALLET_BALANCE: "WALLET_BALANCE",
  EMAIL: "EMAIL",
  USER_PROFILE_DATA: "USER_PROFILE_DATA",
  USER_ACTIVE_STATUS: "USER_ACTIVE_STATUS"
}

export const MYSTERYBOX = {
  CURRENCY_TYPE: "CURRENCY_TYPE",
  BOX_QUANTITY: "BOX_QUANTITY",
  BOX_DETAILS: "BOX_DETAILS",
  BOX_PURCHASE: "BOX_PURCHASE",
  GET_TRANSFER_BOX_DETAILS: "GET_TRANSFER_BOX_DETAILS",
  BOX_NOTIFICATION_STATUS: "BOX_NOTIFICATION_STATUS",
  OPEN_BOX_DETAILS: "OPEN_BOX_DETAILS",
  OPEN_BOX_STATUS: "OPEN_BOX_STATUS"
}

export const USERDETAILS = {
  USER_ALL_HEROES_LIST: "USER_ALL_HEROES_LIST",
  USER_HERO_SALE_TOKEN: "USER_SALE_HERO_TOKEN",
  USER_SALE_NFT_MARKETID: "USER_SALE_NFT_MARKETID",
  USER_NFT_STATUS: "USER_NFT_STATUS",
  USER_NFT_SALE_STATUS: "USER_NFT_SALE_STATUS",
  USER_NFT_BUY_DETAILS: "USER_NFT_BUY_DETAILS",
  USER_NFT_BUY_HASH: "USER_NFT_BUY_HASH",
  OPEN_USER_DETAILS_PAGE_NAME: "OPEN_USER_DETAILS_PAGE_NAME",
  USER_WEAPON_NFT_STATUS: "USER_WEAPON_NFT_STATUS",
  USER_SALE_NFT_NAME: "USER_SALE_NFT_NAME",
  USER_WEAPON_ONSALE_STATUS: "USER_WEAPON_ONSALE_STATUS",
  USER_NFT_UPGRADE_DETAILS: "USER_NFT_UPGRADE_DETAILS",
}

export const MARKETPLACE = {
  HERO_RARITY_ID: "HERO_RARITY_ID",
  SELECTED_HERO_INDEX: "SELECTED_HERO_INDEX",
}